pipeline {
    agent any
    
    environment {
        // mention docker username !!
        DOCKER_IMAGE = "dockerhub_username/flask-app"
        IMAGE_TAG = "build-${env.BUILD_NUMBER}" 
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-creds', 
                    url: 'https://github.com/GITHUB_USERNAME/REPO_NAME.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${DOCKER_IMAGE}:${IMAGE_TAG}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    // docker cred name !!
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        dockerImage.push()
                        dockerImage.push('latest') 
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                // kubeconfig cred file name !!
                withKubeConfig([credentialsId: 'k8s-kubeconfig']) {
                    sh """
                    # Update the deployment file with the new image tag
                    sed -i "s|YOUR_DOCKERHUB_USERNAME/flask-app:latest|${DOCKER_IMAGE}:${IMAGE_TAG}|g" k8s/deployment.yaml
                    
                    # Apply the changes to the cluster
                    kubectl apply -f k8s/deployment.yaml
                    kubectl apply -f k8s/service.yaml
                    """
                }
            }
        }
    }
}