#!/bin/bash

# Firewall for workers !
sudo systemctl start firewalld
sudo systemctl enable firewalld

sudo firewall-cmd --permanent --add-port=6443/tcp
sudo firewall-cmd --permanent --add-port=10250/tcp
sudo firewall-cmd --permanent --add-port=30000-32767/tcp
sudo firewall-cmd --permanent --add-port=4789/udp

sudo firewall-cmd --reload

# Installing mandatory networking packages 
sudo apt-get update -y
sudo apt-get install -y conntrack socat ipset

# Setting up containerd and K8s
sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

# Applying containerd changes immediately
sudo systemctl daemon-reload
sudo systemctl restart containerd

# Joining key for connecting workers nodes to master
echo ""
echo "========================================================================="
echo "Worker node preparation complete."
echo "To join this worker to the cluster, paste the join command generated by"
echo "your master node and append the following flag to it:"
echo "  --cri-socket unix:///var/run/containerd/containerd.sock"
echo ""
echo "Example:"
echo "sudo kubeadm join <master-ip>:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash> --cri-socket unix:///var/run/containerd/containerd.sock"
echo "========================================================================="